### ISSUE TITLE
Anime world Is not working and it is not http 404 error 


### ISSUE THREAD

**Issue by PlayGasty** [almightyhak/aniyomi-anime-repo#10]
Italian anime world is not working on aniyomi

**Comment by mobby45** [comment]
error has been identified  : java.lang.ClassCastException: eu.kanade.tachiyomi.animeextension.it.animeworld.ANIMEWORLD$videosFromElement$$inlined$parallelCatchingFlatMapBlocking$1 cannot be cast to kotlin.jvm.functions.Function2

Error type from the fucntion videos from element supposedly due to Pair Function

**Comment by PlayGasty** [comment]
Do you know how much time it'll take you to repair the error?

**Comment by mobby45** [comment]
a certain time since someone reply on the discord

**Comment by mobby45** [comment]
Issue Closed i did a pull request
